[visualization]
export = true
export_interval = 2

	[[visualize_sim_object]]
	name = "Cell"
	additional_data_members = [ "diameter_" ]

	[[visualize_diffusion]]
	name = "Substance"
	gradient = true

	[[visualize_diffusion]]
	name = "SecondOne"
	gradient = true